### ISSUE TITLE
Provide Chef recipe to provision machines with Selenium-Grid-Extras

### ISSUE THREAD

**Issue by elgalu** [groupon/Selenium-Grid-Extras#126]
It would be nice to have some infrastructure as code the leverages the installation and setup of Selenium-Grid-Extras via Opscode Chef or some other provisioning tool.

**Comment by smccarthy** [comment]
I am going to try and create or help create a cookbook for Selenium-Grid-Extras.  Though it has been awhile since I used chef, so it may take a little bit.

**Comment by smccarthy** [comment]
Hi @elgalu I started to create a chef recipe for Selenium-Grid-Extras.
https://github.com/smccarthy/chef-selenium-grid-extras
I am sure it could use some work, but I tested it a little bit on windows and OSX. Let me know if you run into any issues, especially since I am very new to Chef and cookbooks, and could use all the feedback possible.

Thank you.

**Comment by smccarthy** [comment]
Closing this , as a chef recipe is created (in the works).
