### ISSUE TITLE
Could not find or load main class org.openqa.grid.selenium.GridLauncher

### ISSUE THREAD

**Issue by glacier6327** [groupon/Selenium-Grid-Extras#197]
Need a little help here. 

I followed the directions and ran the hub setup and the grid hub fails to launch

It throws an error: Could not find or load main class org.openqa.grid.selenium.GridLauncher

C:\Grid\test>java  -Dwebdriver.ie.driver=\tmp\webdriver\iedriver\iedriver_2.50.0
_Win32bit.exe -Dwebdriver.edge.driver="C:\Program Files (x86)\Microsoft Web Driv
er\MicrosoftWebDriver.exe" -Dwebdriver.chrome.driver=\tmp\webdriver\chromedriver
\chromedriver_2.21_32bit.exe -cp "C:\Grid\test\SeleniumGridExtras.jar;\tmp\webdr
iver\2.50.1.jar" org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostNa
me CVG-000211M-232 -nodeConfig node_5555.json -log log\node_5555.log
Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher

I swear I have read everything I can find, but nothing explains this...

How does Grid Extras Launch the Grid Node or Hub? Do you have to tell it where it is?

What am I doing wrong?

Thanks,

**Comment by glacier6327** [comment]
This was being caused on my end by older versions of java on my nodes....Resolved

**Comment by hmacias** [comment]
Hi glacier6327

I am seeing a similar error in the logs when I try to launch a node on CentOS using OpenJDK 1.8.0.77-0.


This is the only error I get in the logs:

30 Mar 2016 09:02:58 [pool-1-thread-1] INFO  threads.ExecuteOsTaskCallable  - Command finished. 
 command: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.77-0.b03.el7_2.x86_64/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.21_32bit -cp /root/Selenium_Grid/SeleniumGridExtras-1.11.8-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.53.0.jar org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName localhost.localdomain -nodeConfig node_5555.json -log log/node_5555.log 
 exit code: 1 
 standard error: 
 Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher


This is the latest JRE available in YUM repos. Do you know if there are any compatibility issues with this?

**Comment by hmacias** [comment]
Further troubleshooting results (still not working) on CentOS 7. I installed Oracle's JDK instead of the JRE alone to see if it had anything to do with it: 

java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

But this issue does not seems to have to do with my java version

I keep getting the same error:


30 Mar 2016 09:49:22 [main] INFO  seleniumgridextras.SeleniumGridExtras  - Loaded Grid Logger from log4j.properties
30 Mar 2016 09:49:22 [main] INFO  remote.ConfigPuller  - Config file storing central repository URL is /root/Selenium_Grid/configs/central_config_repo_config.txt
30 Mar 2016 09:49:22 [main] INFO  remote.ConfigPuller  - Central config URL for current node is set to 'http://192.168.100.7:3000/get_node_config?node=localhost.localdomain'
30 Mar 2016 09:49:22 [main] INFO  remote.ConfigPuller  - Checking central Config repository for localhost.localdomain node's config from http://192.168.100.7:3000/get_node_config?node=localhost.localdomain . (Timeout set to 5000ms)
30 Mar 2016 09:49:22 [main] INFO  remote.ConfigPuller  - Remote server responded with this exit code to our request 0
30 Mar 2016 09:49:22 [main] INFO  remote.ConfigPuller  - Updated 'node_5555.json' from central config repository
30 Mar 2016 09:49:22 [main] INFO  remote.ConfigPuller  - Updated 'selenium_grid_extras_config.json' from central config repository
30 Mar 2016 09:49:22 [main] INFO  grid.SelfHealingGrid  - GridExtras is not running will boot normally
30 Mar 2016 09:49:22 [main] INFO  seleniumgridextras.SeleniumGridExtras  - Initializing Task Modules
30 Mar 2016 09:49:22 [main] INFO  tasks.DeleteOldLogsTask  - Deleting all Logs bigger than 20000000 bytes from /root/Selenium_Grid/log
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y DeleteOldLogsTask - /log_delete - Delete logs older than X Days. X is define in the config.json
30 Mar 2016 09:49:22 [main] INFO  tasks.Setup  - Setup Tasks
30 Mar 2016 09:49:22 [main] INFO  tasks.Teardown  - Tear-Down Tasks
30 Mar 2016 09:49:22 [main] INFO  tasks.Teardown  -     MoveMouse
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y MoveMouse - /move_mouse - Moves the computers mouse to x and y location. (Default 0,0)
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y RebootNode - /reboot - Restart the host node
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y VideoRecorder - /video - Starts and stops video recording
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y KillAllIE - /kill_ie - Executes os level kill command on all instance of Internet Explorer
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y KillAllFirefox - /kill_firefox - Executes os level kill command on all instance of Firefox
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y KillAllChrome - /kill_chrome - Executes os level kill command on all instance of Google Chrome
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y KillAllSafari - /kill_safari - Executes os level kill command on all instance of Safari
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y SetAutoLogonUser - /user_auto_logon - Sets a user to automatically logon into system post reboot
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y GetProcesses - /ps - Gets a list of currently running processes
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y KillPid - /kill_pid - Kills a given process id
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y Netstat - /netstat - Returns a system call for all ports. Use /port_info to get parsed details
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y Screenshot - /screenshot - Take a full OS screen Screen Shot of the node
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y ExposeDirectory - /dir - Gives accesses to a shared directory, user has access to put files into it and get files from it. Directory deleted on restart.
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y StartGrid - /start_grid - Starts an instance of Selenium Grid Hub or NodeConfig
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y GetInfoForPort - /port_info - Returns parsed information on a PID occupying a given port
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y GridStatus - /grid_status - Returns status of the Selenium Grid hub/node. If currently running and what is the PID
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y KillAllByName - /kill_all_by_name - Executes os level kill command on a given PID name
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y StopGrid - /stop_grid - Stops grid or node process
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y GetConfig - /config - Returns JSON view of the full configuration of the Selenium Grid Extras
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y StopGridExtras - /stop_extras - Shuts down Grid Extras service
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y IEProtectedMode - /ie_protected_mode - Changes protected mode for Internet Explorer on/off. No param for current status
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y IEMixedContent - /ie_mixed_content - Changes mixed content for Internet Explorer on/off. No param for current status
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y SystemInfo - /system - Returns system details about the current node
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y GetNodeConfig - /get_node_config - Provides the grid node config from central location
30 Mar 2016 09:49:22 [main] INFO  tasks.ExecuteOSTask  - Y UpdateNodeConfig - /update_node_config - Send the current config to the central location to be stored
30 Mar 2016 09:49:22 [main] INFO  webdriverreleasemanager.WebDriverReleaseManager  - Checking the latest version of WebDriver, IEDriver, ChromeDriver from https://selenium-release.storage.googleapis.com/ and https://chromedriver.storage.googleapis.com/LATEST_RELEASE
30 Mar 2016 09:49:23 [main] INFO  tasks.ExecuteOSTask  - Y AutoUpgradeDrivers - /auto_upgrade_webdriver - Automatically checks the latest versions of all drivers and upgrades the current config to use them
30 Mar 2016 09:49:23 [main] INFO  tasks.ExecuteOSTask  - Y DownloadWebdriver - /download_webdriver - Downloads a version of WebDriver jar to local machine
30 Mar 2016 09:49:23 [main] INFO  tasks.ExecuteOSTask  - Y DownloadIEDriver - /download_iedriver - Downloads a version of IEDriver.exe to local machine
30 Mar 2016 09:49:23 [main] INFO  tasks.ExecuteOSTask  - Y DownloadChromeDriver - /download_chromedriver - Downloads a version of ChromeDriver to local machine
30 Mar 2016 09:49:23 [main] INFO  tasks.ExecuteOSTask  - Y SessionHistory - /session_history - Displays the threads of test session on all nodes or per node basis
30 Mar 2016 09:49:23 [main] INFO  tasks.ExecuteOSTask  - Y UpgradeGridExtrasTask - /upgrade_grid_extras - Download specified version of Selenium Grid Extras
30 Mar 2016 09:49:23 [main] INFO  tasks.UpgradeGridExtrasTask  - 
30 Mar 2016 09:49:23 [main] INFO  seleniumgridextras.SeleniumGridExtras  - API documentation
30 Mar 2016 09:49:23 [main] INFO  seleniumgridextras.SeleniumGridExtras  - /api - Located here
30 Mar 2016 09:49:23 [main] INFO  seleniumgridextras.SeleniumGridExtras  - Attaching video downloading context at /download_video
30 Mar 2016 09:49:23 [main] INFO  seleniumgridextras.SeleniumGridExtras  - Grid NodeConfig was set to Autostart
30 Mar 2016 09:49:23 [main] INFO  remote.ConfigPuller  - Config file storing central repository URL is /root/Selenium_Grid/configs/central_config_repo_config.txt
30 Mar 2016 09:49:23 [main] INFO  remote.ConfigPuller  - Central config URL for current node is set to 'http://192.168.100.7:3000/get_node_config?node=localhost.localdomain'
30 Mar 2016 09:49:23 [main] INFO  remote.ConfigPuller  - Checking central Config repository for localhost.localdomain node's config from http://192.168.100.7:3000/get_node_config?node=localhost.localdomain . (Timeout set to 5000ms)
30 Mar 2016 09:49:23 [main] INFO  remote.ConfigPuller  - Remote server responded with this exit code to our request 0
30 Mar 2016 09:49:23 [main] INFO  remote.ConfigPuller  - Updated 'node_5555.json' from central config repository
30 Mar 2016 09:49:23 [main] INFO  remote.ConfigPuller  - Updated 'selenium_grid_extras_config.json' from central config repository
30 Mar 2016 09:49:23 [main] INFO  tasks.StartGrid  - Attempting to start Grid Nodes
30 Mar 2016 09:49:23 [main] INFO  config.Config  - 
30 Mar 2016 09:49:23 [main] INFO  config.Config  - {}
30 Mar 2016 09:49:23 [main] INFO  grid.GridStarter  - Node Start Command: 

[/usr/java/jdk1.8.0_77/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.21_32bit -cp /root/Selenium_Grid/SeleniumGridExtras-1.11.8-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.53.0.jar org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName localhost.localdomain -nodeConfig node_5555.json -log log/node_5555.log]
30 Mar 2016 09:49:23 [main] INFO  grid.GridStarter  - /usr/java/jdk1.8.0_77/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.21_32bit -cp /root/Selenium_Grid/SeleniumGridExtras-1.11.8-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.53.0.jar org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName localhost.localdomain -nodeConfig node_5555.json -log log/node_5555.log
30 Mar 2016 09:49:23 [main] INFO  threads.CommonThreadPool  - Initializing new class com.groupon.seleniumgridextras.utilities.threads.CommonThreadPool
30 Mar 2016 09:49:23 [main] INFO  grid.GridStarter  - {"exit_code":0,"out":["Background process started, check log for output"],"error":[],"command":["/usr/java/jdk1.8.0_77/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.21_32bit -cp /root/Selenium_Grid/SeleniumGridExtras-1.11.8-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.53.0.jar org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName localhost.localdomain -nodeConfig node_5555.json -log log/node_5555.log"]}
30 Mar 2016 09:49:23 [main] INFO  seleniumgridextras.SeleniumGridExtras  - {"exit_code":0,"out":[],"error":[]}
30 Mar 2016 09:49:23 [pool-1-thread-1] INFO  threads.ExecuteOsTaskCallable  - Starting to wait for command to finish in background: /usr/java/jdk1.8.0_77/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.21_32bit -cp /root/Selenium_Grid/SeleniumGridExtras-1.11.8-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.53.0.jar org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName localhost.localdomain -nodeConfig node_5555.json -log log/node_5555.log
30 Mar 2016 09:49:23 [main] INFO  seleniumgridextras.SeleniumGridExtras  - 
Selenium Grid Extras has been started!
Navigate to http://127.0.0.1:3000 for more details
30 Mar 2016 09:49:23 [main] INFO  shutdownhooks.VideoShutdownHook  - Creating instance of the video shutdown hook
30 Mar 2016 09:49:23 [main] INFO  shutdownhooks.VideoShutdownHook  - Video Render Shut Down Hook Attached.
30 Mar 2016 09:49:23 [main] INFO  shutdownhooks.CleanTempShutdownHook  - Creating instance of the clean temp shutdown hook
30 Mar 2016 09:49:23 [pool-1-thread-1] INFO  threads.ExecuteOsTaskCallable  - Command finished. 
 command: /usr/java/jdk1.8.0_77/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.21_32bit -cp /root/Selenium_Grid/SeleniumGridExtras-1.11.8-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.53.0.jar org.openqa.grid.selenium.GridLauncher -role wd  -friendlyHostName localhost.localdomain -nodeConfig node_5555.json -log log/node_5555.log 
 exit code: 1 
 standard error: 
 Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher


By the way, I know this issue has been closed already, but I decided to keep asking here just in case you can still provide some helpful feedback for others googling the same error...

Thanks!

**Comment by robertomoutinho** [comment]
got the same problem over here

```
Selenium Grid Extras has been started!
Navigate to http://127.0.0.1:3000 for more details
06 Oct 2016 03:38:43 [main] INFO  shutdownhooks.VideoShutdownHook  - Creating instance of the video shutdown hook
06 Oct 2016 03:38:43 [main] INFO  shutdownhooks.VideoShutdownHook  - Video Render Shut Down Hook Attached.
06 Oct 2016 03:38:43 [main] INFO  shutdownhooks.CleanTempShutdownHook  - Creating instance of the clean temp shutdown hook
06 Oct 2016 03:38:43 [pool-1-thread-1] INFO  threads.ExecuteOsTaskCallable  - Command finished.
 command: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -cp /opt/intelie/selenium-grid-extra/SeleniumGridExtras-1.12.3-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/2.53.1.jar org.openqa.grid.selenium.GridLauncher -role hub  -log log/hub_4444.log -hubConfig hub_4444.json
 exit code: 1
 standard error:
 Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher
```

**Comment by smccarthy** [comment]
@robertomoutinho I haven't been able to reproduce this issue. Can you try a few things? Either upgrade to openjdk 8, and/or oracle jdk 8 ?

I do think selenium 3 has a new classpath, but it looks like both you and @hmacias are both on selenium 2.53

**Comment by robertomoutinho** [comment]
It had to do with a bad param being passed in the java -jar execution (*-Dwebdriver.firefox.bin*)... 
taking out the param from the execution script brought things back to normal.
