### ISSUE TITLE
Several Nodes on same Host is broken

### ISSUE THREAD

**Issue by vitrilo** [groupon/Selenium-Grid-Extras#283]
Currently two Node instances on same host is not working:

1. Selenium Server Node process get wrongly created with command line parameter  id=getHostName(), which effectively disallow several nodes per host in HUB (each time one Node will get replace other with same Node ID).
    - This bug was injected while adding WebDriver 3.0 support in (GridStarter.java line 327). WebDriver 2.0 and 1.0 is not affected. 
2. Video bug - Logged separately  as #284, its also a blocker, because several Nades on same host will have all custom ports (deferent from 5555 and 3000).

For 1- I'm just about to create Pull Request.
For 2 - Moved as https://github.com/groupon/Selenium-Grid-Extras/issues/284

**Comment by smccarthy** [comment]
For #2, What is http://10.8.22.50:3000 ? A hub or node?

Also, did you change any ports around? Or is your nodes using port 5555 and your hub using port 4444 and you selenium-grid-extras service using port 3000 ? You mention 2 nodes on the same machine, so trying to confirm.

Thank you.

**Comment by vitrilo** [comment]
@smccarthy I've confirmed Issue2 and moved it to separate issue (becouse it reproduced even with single node).

**Comment by vitrilo** [comment]
@smccarthy I feel like my setup (several Nodes on same host) is uncommon usage of Selenium-Grid-Extras. Can you help me refine my setup and provide some suggestions?

I want build a small Selenium Grid cloud. I want to have video records for EACH selenium test run (green or red). 
1. As Selenium-Grid-Extras record a whole Desktop, apart from browser window - I'm forced to use maxSession=1, right? In other case - browser windows (separate selenium sessions) will hide each-other in the video, making video not very useful. 
2. I need about 50 nodes, so I have only two options: 

    a. 50 small Linux instances with single XOrg-xvfb/Selenium-Grid-Extras
    b. 1-2 big Linux instances with 25-50 XOrg-xvfb destops/Selenium-Grid-Extras inside in each.

Did common setup is 2 a?

**Comment by smccarthy** [comment]
@vitrilo I normally see 1 node per VM/machine. I don't see a need to have more than 1, unless you are talking about containers (multiple docker-selenium containers per machine/VM). I actually think you could run into issues running 2 Selenium Grid Extras on the same machine/VM. Things like auto reboot might not work correctly.

Videos are OS-level, so it doesn't matter if you run 2 nodes on a host, or 1 node that can run 2 browsers at once. You will run into issues. The way around that is to run 1 node per host, and that 1 node can only run 1 test/browser at a time. Otherwise you could have overlapping of browser windows.

1) Yes, maxSession = 1 per node

2) I really don't have much experience with 2b, but that's not to say its not a good setup. Both should work, so which ever is better for you, try it out. I am curious on your results.

**Comment by smccarthy** [comment]
I merged the PR to fix the first issue.

Looks good. I didn't realize we couldn't have 2 nodes with the same id. I just wanted an easier way to see on the grid hub console which node goes to which hostname.

**Comment by smccarthy** [comment]
Closing this. I made a release, v1.12.10 with this fix. Someone else had the same issue, and verified it's fixed. Thank you @vitrilo !
