### ISSUE TITLE
log4j:ERROR Failed to rename...

### ISSUE THREAD

**Issue by cktech529** [groupon/Selenium-Grid-Extras#87]
I'm seeing this constantly on the hub (using the latest 1.7.1 snapshot)

Selenium Grid Extras has been started!
Navigate to http://localhost:3000 for more details
log4j:ERROR Failed to rename [log//grid_extras.log] to [log//grid_extras.log.201
5-02-05].

**Comment by smccarthy** [comment]
A quick search brought me here : http://stackoverflow.com/questions/13410189/log4jerror-failed-to-rename . It appears to be a problem with Windows only.

**Comment by smccarthy** [comment]
Updating log4j from 1.2.14 to 1.2.16 or 1.2.17 might work.

**Comment by smccarthy** [comment]
@cktech529 Can you try to upgrade log4j (to 1.2.16 or 1.2.17) and test it out to see if it fixes the issue for you? It seems to work for me, but I don't think I hit the error with the current version of log4j (1.2.14) either. I will try again when I get into the office tomorrow as well.

To try yourself, checkout the Selenium-Grid-Extras project from github, update the pom.xml to update log4j version from 1.2.14 to 1.2.17 (of .16), than do a mvn clean install , and you will get the updated Selenium-Grid-Extras jar.

Thanks !

**Comment by rgonalo** [comment]
Hi @smccarthy, log4j 1.2.16 and 1.2.17 don't fix the issue in Windows. It's neccessary to use log4j-extras 1.2.17 and use RollingFileAppender instead of DailyRollingFileAppender.
This pull request (https://github.com/groupon/Selenium-Grid-Extras/pull/89) fixes the issue, but it changes the name of the active grid log from grid_extras.log to grid_extras.2015-02-09.log and I'm not sure if this could be a problem to someone.

**Comment by smccarthy** [comment]
@rgonalo Awesome thanks !

**Comment by cktech529** [comment]
Thanks everyone, pardon the late reply here, went away after posting this. @rgonalo, I will try that.

**Comment by smccarthy** [comment]
@cktech529 This is already merged in master, but not a downloadable release. Feel free to build from source though : mvn clean install ,will build the jar.
